part of '../../../sdl.dart';

///
/// Get an array including all versions of a surface.
///
/// This returns all versions of a surface, with the surface being queried as
/// the first element in the returned array.
///
/// Freeing the array of surfaces does not affect the surfaces in the array.
/// They are still referenced by the surface being queried and will be cleaned
/// up normally.
///
/// \param surface the SDL_Surface structure to query.
/// \param count a pointer filled in with the number of surface pointers
/// returned, may be NULL.
/// \returns a NULL terminated array of SDL_Surface pointers or NULL on
/// failure; call SDL_GetError() for more information. This should be
/// freed with SDL_free() when it is no longer needed.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_AddSurfaceAlternateImage
/// \sa SDL_RemoveSurfaceAlternateImages
/// \sa SDL_SurfaceHasAlternateImages
///
/// ```c
/// extern SDL_DECLSPEC SDL_Surface ** SDLCALL SDL_GetSurfaceImages(SDL_Surface *surface, int *count)
/// ```
/// {@category surface}
List<Pointer<SdlSurface>> sdlxGetSurfaceImages(Pointer<SdlSurface> surface) {
  final countPointer = ffi.calloc<Int32>();
  final images = <Pointer<SdlSurface>>[];
  final imagesPointer = sdlGetSurfaceImages(surface, countPointer);
  if (countPointer.value > 0) {
    for (var i = 0; i < countPointer.value; i++) {
      images.add(imagesPointer[i]);
    }
  }
  countPointer.callocFree();
  return images;
}

///
/// Get the color key (transparent pixel) for a surface.
///
/// The color key is a pixel of the format used by the surface, as generated by
/// SDL_MapRGB().
///
/// If the surface doesn't have color key enabled this function returns false.
///
/// \param surface the SDL_Surface structure to query.
/// \param key a pointer filled in with the transparent pixel.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety It is safe to call this function from any thread.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_SetSurfaceColorKey
/// \sa SDL_SurfaceHasColorKey
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceColorKey(SDL_Surface *surface, Uint32 *key)
/// ```
/// {@category surface}
int? sdlxGetSurfaceColorKey(Pointer<SdlSurface> surface) {
  int? result;
  final keyPointer = ffi.calloc<Uint32>();
  final bl = sdlGetSurfaceColorKey(surface, keyPointer);
  if (bl) {
    result = keyPointer.value;
  }
  keyPointer.callocFree();
  return result;
}

///
/// Set an additional color value multiplied into blit operations.
///
/// When this surface is blitted, during the blit operation each source color
/// channel is modulated by the appropriate color value according to the
/// following formula:
///
/// `srcC = srcC * (color / 255)`
///
/// \param surface the SDL_Surface structure to update.
/// \param r the red color value multiplied into blit operations.
/// \param g the green color value multiplied into blit operations.
/// \param b the blue color value multiplied into blit operations.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_GetSurfaceColorMod
/// \sa SDL_SetSurfaceAlphaMod
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorMod(SDL_Surface *surface, Uint8 r, Uint8 g, Uint8 b)
/// ```
/// {@category surface}
bool sdlxSetSurfaceColorMod(Pointer<SdlSurface> surface, SdlxColor color) {
  var result = sdlSetSurfaceColorMod(surface, color.r, color.g, color.b);
  if (result) {
    result = sdlSetSurfaceAlphaMod(surface, color.a);
  }
  return result;
}

///
/// Get the additional color value multiplied into blit operations.
///
/// \param surface the SDL_Surface structure to query.
/// \param r a pointer filled in with the current red color value.
/// \param g a pointer filled in with the current green color value.
/// \param b a pointer filled in with the current blue color value.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_GetSurfaceAlphaMod
/// \sa SDL_SetSurfaceColorMod
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceColorMod(SDL_Surface *surface, Uint8 *r, Uint8 *g, Uint8 *b)
/// ```
/// {@category surface}
bool sdlxGetSurfaceColorMod(Pointer<SdlSurface> surface, SdlxColor color) {
  final rPointer = ffi.calloc<Uint8>();
  final gPointer = ffi.calloc<Uint8>();
  final bPointer = ffi.calloc<Uint8>();
  final aPointer = ffi.calloc<Uint8>();
  var result = sdlGetSurfaceColorMod(surface, rPointer, gPointer, bPointer);
  if (result) {
    color
      ..r = rPointer.value
      ..g = gPointer.value
      ..b = bPointer.value;
    result = sdlGetSurfaceAlphaMod(surface, aPointer);
    if (result) {
      color.a = aPointer.value;
    }
  }
  rPointer.callocFree();
  gPointer.callocFree();
  bPointer.callocFree();
  aPointer.callocFree();
  return result;
}

///
/// Get the blend mode used for blit operations.
///
/// \param surface the SDL_Surface structure to query.
/// \param blendMode a pointer filled in with the current SDL_BlendMode.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety It is safe to call this function from any thread.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_SetSurfaceBlendMode
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceBlendMode(SDL_Surface *surface, SDL_BlendMode *blendMode)
/// ```
/// {@category surface}
int? sdlxGetSurfaceBlendMode(Pointer<SdlSurface> surface) {
  int? result;
  final blendModePointer = ffi.calloc<Uint32>();
  final bl = sdlGetSurfaceBlendMode(surface, blendModePointer);
  if (bl) {
    result = blendModePointer.value;
  }
  blendModePointer.callocFree();
  return result;
}

///
/// Set the clipping rectangle for a surface.
///
/// When `surface` is the destination of a blit, only the area within the clip
/// rectangle is drawn into.
///
/// Note that blits are automatically clipped to the edges of the source and
/// destination surfaces.
///
/// \param surface the SDL_Surface structure to be clipped.
/// \param rect the SDL_Rect structure representing the clipping rectangle, or
/// NULL to disable clipping.
/// \returns true if the rectangle intersects the surface, otherwise false and
/// blits will be completely clipped.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_GetSurfaceClipRect
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceClipRect(SDL_Surface *surface, const SDL_Rect *rect)
/// ```
/// {@category surface}
bool sdlxSetSurfaceClipRect(Pointer<SdlSurface> surface, SdlxRect? rect) {
  Pointer<SdlRect> rectPointer = nullptr;
  if (rect != null) {
    rectPointer = rect.calloc();
  }
  final result = sdlSetSurfaceClipRect(surface, rectPointer);
  if (rectPointer != nullptr) {
    rectPointer.callocFree();
  }
  return result;
}

///
/// Get the clipping rectangle for a surface.
///
/// When `surface` is the destination of a blit, only the area within the clip
/// rectangle is drawn into.
///
/// \param surface the SDL_Surface structure representing the surface to be
/// clipped.
/// \param rect an SDL_Rect structure filled in with the clipping rectangle for
/// the surface.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_SetSurfaceClipRect
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceClipRect(SDL_Surface *surface, SDL_Rect *rect)
/// ```
/// {@category surface}
bool sdlxGetSurfaceClipRect(Pointer<SdlSurface> surface, SdlxRect rect) {
  final rectPointer = rect.calloc();
  final result = sdlGetSurfaceClipRect(surface, rectPointer);
  if (result) {
    rect.loadFromPointer(rectPointer);
  }
  rectPointer.callocFree();
  return result;
}

///
/// Clear a surface with a specific color, with floating point precision.
///
/// This function handles all surface formats, and ignores any clip rectangle.
///
/// If the surface is YUV, the color is assumed to be in the sRGB colorspace,
/// otherwise the color is assumed to be in the colorspace of the surface.
///
/// \param surface the SDL_Surface to clear.
/// \param r the red component of the pixel, normally in the range 0-1.
/// \param g the green component of the pixel, normally in the range 0-1.
/// \param b the blue component of the pixel, normally in the range 0-1.
/// \param a the alpha component of the pixel, normally in the range 0-1.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_ClearSurface(SDL_Surface *surface, float r, float g, float b, float a)
/// ```
/// {@category surface}
bool sdlxClearSurface(Pointer<SdlSurface> surface, SdlxFColor color) =>
    sdlClearSurface(surface, color.r, color.g, color.b, color.a);

///
/// Perform a fast fill of a rectangle with a specific color.
///
/// `color` should be a pixel of the format used by the surface, and can be
/// generated by SDL_MapRGB() or SDL_MapRGBA(). If the color value contains an
/// alpha component then the destination is simply filled with that alpha
/// information, no blending takes place.
///
/// If there is a clip rectangle set on the destination (set via
/// SDL_SetSurfaceClipRect()), then this function will fill based on the
/// intersection of the clip rectangle and `rect`.
///
/// \param dst the SDL_Surface structure that is the drawing target.
/// \param rect the SDL_Rect structure representing the rectangle to fill, or
/// NULL to fill the entire surface.
/// \param color the color to fill with.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_FillSurfaceRects
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_FillSurfaceRect(SDL_Surface *dst, const SDL_Rect *rect, Uint32 color)
/// ```
/// {@category surface}
bool sdlxFillSurfaceRect(Pointer<SdlSurface> dst, SdlxRect? rect, int color) {
  Pointer<SdlRect> rectPointer = nullptr;
  if (rect != null) {
    rectPointer = rect.calloc();
  }
  final result = sdlFillSurfaceRect(dst, rectPointer, color);
  if (rectPointer != nullptr) {
    rectPointer.callocFree();
  }
  return result;
}

///
/// Perform a fast fill of a set of rectangles with a specific color.
///
/// `color` should be a pixel of the format used by the surface, and can be
/// generated by SDL_MapRGB() or SDL_MapRGBA(). If the color value contains an
/// alpha component then the destination is simply filled with that alpha
/// information, no blending takes place.
///
/// If there is a clip rectangle set on the destination (set via
/// SDL_SetSurfaceClipRect()), then this function will fill based on the
/// intersection of the clip rectangle and `rect`.
///
/// \param dst the SDL_Surface structure that is the drawing target.
/// \param rects an array of SDL_Rects representing the rectangles to fill.
/// \param count the number of rectangles in the array.
/// \param color the color to fill with.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_FillSurfaceRect
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_FillSurfaceRects(SDL_Surface *dst, const SDL_Rect *rects, int count, Uint32 color)
/// ```
/// {@category surface}
bool sdlxFillSurfaceRects(
  Pointer<SdlSurface> dst,
  List<SdlxRect> rects,
  int color,
) {
  final count = rects.length;
  final rectsPointer = ffi.calloc<SdlRect>(count);
  for (var i = 0; i < count; i++) {
    final _ = rectsPointer[i]
      ..x = rects[i].x
      ..y = rects[i].y
      ..w = rects[i].w
      ..h = rects[i].h;
  }
  final result = sdlFillSurfaceRects(dst, rectsPointer, count, color);
  rectsPointer.callocFree();
  return result;
}

///
/// Performs a fast blit from the source surface to the destination surface
/// with clipping.
///
/// If either `srcrect` or `dstrect` are NULL, the entire surface (`src` or
/// `dst`) is copied while ensuring clipping to `dst->clip_rect`.
///
/// The blit function should not be called on a locked surface.
///
/// The blit semantics for surfaces with and without blending and colorkey are
/// defined as follows:
///
/// ===
/// RGBA->RGB:
/// Source surface blend mode set to SDL_BLENDMODE_BLEND:
/// alpha-blend (using the source alpha-channel and per-surface alpha)
/// SDL_SRCCOLORKEY ignored.
/// Source surface blend mode set to SDL_BLENDMODE_NONE:
/// copy RGB.
/// if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
/// RGB values of the source color key, ignoring alpha in the
/// comparison.
///
/// RGB->RGBA:
/// Source surface blend mode set to SDL_BLENDMODE_BLEND:
/// alpha-blend (using the source per-surface alpha)
/// Source surface blend mode set to SDL_BLENDMODE_NONE:
/// copy RGB, set destination alpha to source per-surface alpha value.
/// both:
/// if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
/// source color key.
///
/// RGBA->RGBA:
/// Source surface blend mode set to SDL_BLENDMODE_BLEND:
/// alpha-blend (using the source alpha-channel and per-surface alpha)
/// SDL_SRCCOLORKEY ignored.
/// Source surface blend mode set to SDL_BLENDMODE_NONE:
/// copy all of RGBA to the destination.
/// if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
/// RGB values of the source color key, ignoring alpha in the
/// comparison.
///
/// RGB->RGB:
/// Source surface blend mode set to SDL_BLENDMODE_BLEND:
/// alpha-blend (using the source per-surface alpha)
/// Source surface blend mode set to SDL_BLENDMODE_NONE:
/// copy RGB.
/// both:
/// if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
/// source color key.
/// ===
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, or NULL to copy the entire surface.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the x and y position in
/// the destination surface, or NULL for (0,0). The width and
/// height are ignored, and are copied from `srcrect`. If you
/// want a specific width and height, you should use
/// SDL_BlitSurfaceScaled().
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurfaceScaled
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurface(SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
/// ```
/// {@category surface}
bool sdlxBlitSurface(
  Pointer<SdlSurface> src,
  SdlxRect? srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect? dstrect,
) {
  Pointer<SdlRect> srcrectPointer = nullptr;
  Pointer<SdlRect> dstrectPointer = nullptr;
  if (srcrect != null) {
    srcrectPointer = srcrect.calloc();
  }
  if (dstrect != null) {
    dstrectPointer = dstrect.calloc();
  }
  final result = sdlBlitSurface(src, srcrectPointer, dst, dstrectPointer);
  if (srcrectPointer != nullptr) {
    srcrectPointer.callocFree();
  }
  if (dstrectPointer != nullptr) {
    dstrectPointer.callocFree();
  }
  return result;
}

///
/// Perform low-level surface blitting only.
///
/// This is a semi-private blit function and it performs low-level surface
/// blitting, assuming the input rectangles have already been clipped.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, may not be NULL.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, may not be NULL.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurface
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceUnchecked(SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
/// ```
/// {@category surface}
bool sdlxBlitSurfaceUnchecked(
  Pointer<SdlSurface> src,
  SdlxRect srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect dstrect,
) {
  final srcrectPointer = srcrect.calloc();
  final dstrectPointer = dstrect.calloc();
  final result = sdlBlitSurfaceUnchecked(
    src,
    srcrectPointer,
    dst,
    dstrectPointer,
  );
  srcrectPointer.callocFree();
  dstrectPointer.callocFree();
  return result;
}

///
/// Perform a scaled blit to a destination surface, which may be of a different
/// format.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, or NULL to copy the entire surface.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, or NULL to fill the entire
/// destination surface.
/// \param scaleMode the SDL_ScaleMode to be used.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurface
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceScaled(SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
/// ```
/// {@category surface}
bool sdlxBlitSurfaceScaled(
  Pointer<SdlSurface> src,
  SdlxRect? srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect? dstrect, {
  int scaleMode = SdlkScalemode.invalid,
}) {
  Pointer<SdlRect> srcrectPointer = nullptr;
  Pointer<SdlRect> dstrectPointer = nullptr;
  if (srcrect != null) {
    srcrectPointer = srcrect.calloc();
  }
  if (dstrect != null) {
    dstrectPointer = dstrect.calloc();
  }
  final result = sdlBlitSurfaceScaled(
    src,
    srcrectPointer,
    dst,
    dstrectPointer,
    scaleMode,
  );
  if (srcrectPointer != nullptr) {
    srcrectPointer.callocFree();
  }
  if (dstrectPointer != nullptr) {
    dstrectPointer.callocFree();
  }
  return result;
}

///
/// Perform low-level surface scaled blitting only.
///
/// This is a semi-private function and it performs low-level surface blitting,
/// assuming the input rectangles have already been clipped.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, may not be NULL.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, may not be NULL.
/// \param scaleMode the SDL_ScaleMode to be used.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurfaceScaled
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceUncheckedScaled(SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
/// ```
/// {@category surface}
bool sdlxBlitSurfaceUncheckedScaled(
  Pointer<SdlSurface> src,
  SdlxRect srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect dstrect, {
  int scaleMode = SdlkScalemode.invalid,
}) {
  final srcrectPointer = srcrect.calloc();
  final dstrectPointer = dstrect.calloc();
  final result = sdlBlitSurfaceUncheckedScaled(
    src,
    srcrectPointer,
    dst,
    dstrectPointer,
    scaleMode,
  );
  srcrectPointer.callocFree();
  dstrectPointer.callocFree();
  return result;
}

///
/// Perform a stretched pixel copy from one surface to another.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, or NULL to copy the entire surface.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, or NULL to fill the entire
/// destination surface.
/// \param scaleMode the SDL_ScaleMode to be used.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.4.0.
///
/// \sa SDL_BlitSurfaceScaled
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_StretchSurface(SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
/// ```
/// {@category surface}
bool sdlxStretchSurface(
  Pointer<SdlSurface> src,
  SdlxRect? srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect? dstrect, {
  int scaleMode = SdlkScalemode.invalid,
}) {
  Pointer<SdlRect> srcrectPointer = nullptr;
  Pointer<SdlRect> dstrectPointer = nullptr;
  if (srcrect != null) {
    srcrectPointer = srcrect.calloc();
  }
  if (dstrect != null) {
    dstrectPointer = dstrect.calloc();
  }
  final result = sdlStretchSurface(
    src,
    srcrectPointer,
    dst,
    dstrectPointer,
    scaleMode,
  );
  if (srcrectPointer != nullptr) {
    srcrectPointer.callocFree();
  }
  if (dstrectPointer != nullptr) {
    dstrectPointer.callocFree();
  }
  return result;
}

///
/// Perform a tiled blit to a destination surface, which may be of a different
/// format.
///
/// The pixels in `srcrect` will be repeated as many times as needed to
/// completely fill `dstrect`.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, or NULL to copy the entire surface.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, or NULL to fill the entire surface.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurface
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceTiled(SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
/// ```
/// {@category surface}
bool sdlxBlitSurfaceTiled(
  Pointer<SdlSurface> src,
  SdlxRect? srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect? dstrect,
) {
  Pointer<SdlRect> srcrectPointer = nullptr;
  Pointer<SdlRect> dstrectPointer = nullptr;
  if (srcrect != null) {
    srcrectPointer = srcrect.calloc();
  }
  if (dstrect != null) {
    dstrectPointer = dstrect.calloc();
  }
  final result = sdlBlitSurface(src, srcrectPointer, dst, dstrectPointer);
  if (srcrectPointer != nullptr) {
    srcrectPointer.callocFree();
  }
  if (dstrectPointer != nullptr) {
    dstrectPointer.callocFree();
  }
  return result;
}

///
/// Perform a scaled and tiled blit to a destination surface, which may be of a
/// different format.
///
/// The pixels in `srcrect` will be scaled and repeated as many times as needed
/// to completely fill `dstrect`.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be
/// copied, or NULL to copy the entire surface.
/// \param scale the scale used to transform srcrect into the destination
/// rectangle, e.g. a 32x32 texture with a scale of 2 would fill
/// 64x64 tiles.
/// \param scaleMode scale algorithm to be used.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, or NULL to fill the entire surface.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurface
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceTiledWithScale(SDL_Surface *src, const SDL_Rect *srcrect, float scale, SDL_ScaleMode scaleMode, SDL_Surface *dst, const SDL_Rect *dstrect)
/// ```
/// {@category surface}
bool sdlxBlitSurfaceTiledWithScale(
  Pointer<SdlSurface> src,
  SdlxRect? srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect? dstrect, {
  double scale = 1.0,
  int scaleMode = SdlkScalemode.invalid,
}) {
  Pointer<SdlRect> srcrectPointer = nullptr;
  Pointer<SdlRect> dstrectPointer = nullptr;
  if (srcrect != null) {
    srcrectPointer = srcrect.calloc();
  }
  if (dstrect != null) {
    dstrectPointer = dstrect.calloc();
  }
  final result = sdlBlitSurfaceTiledWithScale(
    src,
    srcrectPointer,
    scale,
    scaleMode,
    dst,
    dstrectPointer,
  );
  if (srcrectPointer != nullptr) {
    srcrectPointer.callocFree();
  }
  if (dstrectPointer != nullptr) {
    dstrectPointer.callocFree();
  }
  return result;
}

///
/// Perform a scaled blit using the 9-grid algorithm to a destination surface,
/// which may be of a different format.
///
/// The pixels in the source surface are split into a 3x3 grid, using the
/// different corner sizes for each corner, and the sides and center making up
/// the remaining pixels. The corners are then scaled using `scale` and fit
/// into the corners of the destination rectangle. The sides and center are
/// then stretched into place to cover the remaining destination rectangle.
///
/// \param src the SDL_Surface structure to be copied from.
/// \param srcrect the SDL_Rect structure representing the rectangle to be used
/// for the 9-grid, or NULL to use the entire surface.
/// \param left_width the width, in pixels, of the left corners in `srcrect`.
/// \param right_width the width, in pixels, of the right corners in `srcrect`.
/// \param top_height the height, in pixels, of the top corners in `srcrect`.
/// \param bottom_height the height, in pixels, of the bottom corners in
/// `srcrect`.
/// \param scale the scale used to transform the corner of `srcrect` into the
/// corner of `dstrect`, or 0.0f for an unscaled blit.
/// \param scaleMode scale algorithm to be used.
/// \param dst the SDL_Surface structure that is the blit target.
/// \param dstrect the SDL_Rect structure representing the target rectangle in
/// the destination surface, or NULL to fill the entire surface.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety Only one thread should be using the `src` and `dst` surfaces
/// at any given time.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_BlitSurface
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_BlitSurface9Grid(SDL_Surface *src, const SDL_Rect *srcrect, int left_width, int right_width, int top_height, int bottom_height, float scale, SDL_ScaleMode scaleMode, SDL_Surface *dst, const SDL_Rect *dstrect)
/// ```
/// {@category surface}
bool sdlxBlitSurface9Grid(
  Pointer<SdlSurface> src,
  SdlxRect? srcrect,
  Pointer<SdlSurface> dst,
  SdlxRect? dstrect, {
  required int leftWidth,
  required int rightWidth,
  required int topHeight,
  required int bottomHeight,
  double scale = 1.0,
  int scaleMode = SdlkScalemode.invalid,
}) {
  Pointer<SdlRect> srcrectPointer = nullptr;
  Pointer<SdlRect> dstrectPointer = nullptr;
  if (srcrect != null) {
    srcrectPointer = srcrect.calloc();
  }
  if (dstrect != null) {
    dstrectPointer = dstrect.calloc();
  }
  final result = sdlBlitSurface9Grid(
    src,
    srcrectPointer,
    leftWidth,
    rightWidth,
    topHeight,
    bottomHeight,
    scale,
    scaleMode,
    dst,
    dstrectPointer,
  );
  if (srcrectPointer != nullptr) {
    srcrectPointer.callocFree();
  }
  if (dstrectPointer != nullptr) {
    dstrectPointer.callocFree();
  }
  return result;
}

///
/// Map an RGB triple to an opaque pixel value for a surface.
///
/// This function maps the RGB color value to the specified pixel format and
/// returns the pixel value best approximating the given RGB color value for
/// the given pixel format.
///
/// If the surface has a palette, the index of the closest matching color in
/// the palette will be returned.
///
/// If the surface pixel format has an alpha component it will be returned as
/// all 1 bits (fully opaque).
///
/// If the pixel format bpp (color depth) is less than 32-bpp then the unused
/// upper bits of the return value can safely be ignored (e.g., with a 16-bpp
/// format the return value can be assigned to a Uint16, and similarly a Uint8
/// for an 8-bpp format).
///
/// \param surface the surface to use for the pixel format and palette.
/// \param r the red component of the pixel in the range 0-255.
/// \param g the green component of the pixel in the range 0-255.
/// \param b the blue component of the pixel in the range 0-255.
/// \returns a pixel value.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_MapSurfaceRGBA
///
/// ```c
/// extern SDL_DECLSPEC Uint32 SDLCALL SDL_MapSurfaceRGB(SDL_Surface *surface, Uint8 r, Uint8 g, Uint8 b)
/// ```
/// {@category surface}
int sdlxMapSurfaceRgb(Pointer<SdlSurface> surface, SdlxColor color) =>
    sdlMapSurfaceRgb(surface, color.r, color.g, color.b);

///
/// Map an RGBA quadruple to a pixel value for a surface.
///
/// This function maps the RGBA color value to the specified pixel format and
/// returns the pixel value best approximating the given RGBA color value for
/// the given pixel format.
///
/// If the surface pixel format has no alpha component the alpha value will be
/// ignored (as it will be in formats with a palette).
///
/// If the surface has a palette, the index of the closest matching color in
/// the palette will be returned.
///
/// If the pixel format bpp (color depth) is less than 32-bpp then the unused
/// upper bits of the return value can safely be ignored (e.g., with a 16-bpp
/// format the return value can be assigned to a Uint16, and similarly a Uint8
/// for an 8-bpp format).
///
/// \param surface the surface to use for the pixel format and palette.
/// \param r the red component of the pixel in the range 0-255.
/// \param g the green component of the pixel in the range 0-255.
/// \param b the blue component of the pixel in the range 0-255.
/// \param a the alpha component of the pixel in the range 0-255.
/// \returns a pixel value.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// \sa SDL_MapSurfaceRGB
///
/// ```c
/// extern SDL_DECLSPEC Uint32 SDLCALL SDL_MapSurfaceRGBA(SDL_Surface *surface, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
/// ```
/// {@category surface}
int sdlxMapSurfaceRgba(Pointer<SdlSurface> surface, SdlxColor color) =>
    sdlMapSurfaceRgba(surface, color.r, color.g, color.b, color.a);

///
/// Retrieves a single pixel from a surface.
///
/// This function prioritizes correctness over speed: it is suitable for unit
/// tests, but is not intended for use in a game engine.
///
/// Like SDL_GetRGBA, this uses the entire 0..255 range when converting color
/// components from pixel formats with less than 8 bits per RGB component.
///
/// \param surface the surface to read.
/// \param x the horizontal coordinate, 0 <= x < width.
/// \param y the vertical coordinate, 0 <= y < height.
/// \param r a pointer filled in with the red channel, 0-255, or NULL to ignore
/// this channel.
/// \param g a pointer filled in with the green channel, 0-255, or NULL to
/// ignore this channel.
/// \param b a pointer filled in with the blue channel, 0-255, or NULL to
/// ignore this channel.
/// \param a a pointer filled in with the alpha channel, 0-255, or NULL to
/// ignore this channel.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_ReadSurfacePixel(SDL_Surface *surface, int x, int y, Uint8 *r, Uint8 *g, Uint8 *b, Uint8 *a)
/// ```
/// {@category surface}
bool sdlxReadSurfacePixel(
  Pointer<SdlSurface> surface,
  SdlxPoint point,
  SdlxColor color,
) {
  final rPointer = ffi.calloc<Uint8>();
  final gPointer = ffi.calloc<Uint8>();
  final bPointer = ffi.calloc<Uint8>();
  final aPointer = ffi.calloc<Uint8>();
  final result = sdlReadSurfacePixel(
    surface,
    point.x,
    point.y,
    rPointer,
    gPointer,
    bPointer,
    aPointer,
  );
  if (result) {
    color
      ..r = rPointer.value
      ..g = gPointer.value
      ..b = bPointer.value
      ..a = aPointer.value;
  }
  rPointer.callocFree();
  gPointer.callocFree();
  bPointer.callocFree();
  aPointer.callocFree();
  return result;
}

///
/// Retrieves a single pixel from a surface.
///
/// This function prioritizes correctness over speed: it is suitable for unit
/// tests, but is not intended for use in a game engine.
///
/// \param surface the surface to read.
/// \param x the horizontal coordinate, 0 <= x < width.
/// \param y the vertical coordinate, 0 <= y < height.
/// \param r a pointer filled in with the red channel, normally in the range
/// 0-1, or NULL to ignore this channel.
/// \param g a pointer filled in with the green channel, normally in the range
/// 0-1, or NULL to ignore this channel.
/// \param b a pointer filled in with the blue channel, normally in the range
/// 0-1, or NULL to ignore this channel.
/// \param a a pointer filled in with the alpha channel, normally in the range
/// 0-1, or NULL to ignore this channel.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_ReadSurfacePixelFloat(SDL_Surface *surface, int x, int y, float *r, float *g, float *b, float *a)
/// ```
/// {@category surface}
bool sdlxReadSurfacePixelFloat(
  Pointer<SdlSurface> surface,
  SdlxPoint point,
  SdlxFColor color,
) {
  final rPointer = ffi.calloc<Float>();
  final gPointer = ffi.calloc<Float>();
  final bPointer = ffi.calloc<Float>();
  final aPointer = ffi.calloc<Float>();
  final result = sdlReadSurfacePixelFloat(
    surface,
    point.x,
    point.y,
    rPointer,
    gPointer,
    bPointer,
    aPointer,
  );
  if (result) {
    color
      ..r = rPointer.value
      ..g = gPointer.value
      ..b = bPointer.value
      ..a = aPointer.value;
  }
  rPointer.callocFree();
  gPointer.callocFree();
  bPointer.callocFree();
  aPointer.callocFree();
  return result;
}

///
/// Writes a single pixel to a surface.
///
/// This function prioritizes correctness over speed: it is suitable for unit
/// tests, but is not intended for use in a game engine.
///
/// Like SDL_MapRGBA, this uses the entire 0..255 range when converting color
/// components from pixel formats with less than 8 bits per RGB component.
///
/// \param surface the surface to write.
/// \param x the horizontal coordinate, 0 <= x < width.
/// \param y the vertical coordinate, 0 <= y < height.
/// \param r the red channel value, 0-255.
/// \param g the green channel value, 0-255.
/// \param b the blue channel value, 0-255.
/// \param a the alpha channel value, 0-255.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_WriteSurfacePixel(SDL_Surface *surface, int x, int y, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
/// ```
/// {@category surface}
bool sdlxWriteSurfacePixel(
  Pointer<SdlSurface> surface,
  SdlxPoint point,
  SdlxColor color,
) => sdlWriteSurfacePixel(
  surface,
  point.x,
  point.y,
  color.r,
  color.g,
  color.b,
  color.a,
);

///
/// Writes a single pixel to a surface.
///
/// This function prioritizes correctness over speed: it is suitable for unit
/// tests, but is not intended for use in a game engine.
///
/// \param surface the surface to write.
/// \param x the horizontal coordinate, 0 <= x < width.
/// \param y the vertical coordinate, 0 <= y < height.
/// \param r the red channel value, normally in the range 0-1.
/// \param g the green channel value, normally in the range 0-1.
/// \param b the blue channel value, normally in the range 0-1.
/// \param a the alpha channel value, normally in the range 0-1.
/// \returns true on success or false on failure; call SDL_GetError() for more
/// information.
///
/// \threadsafety This function can be called on different threads with
/// different surfaces.
///
/// \since This function is available since SDL 3.2.0.
///
/// ```c
/// extern SDL_DECLSPEC bool SDLCALL SDL_WriteSurfacePixelFloat(SDL_Surface *surface, int x, int y, float r, float g, float b, float a)
/// ```
/// {@category surface}
bool sdlxWriteSurfacePixelFloat(
  Pointer<SdlSurface> surface,
  SdlxPoint point,
  SdlxFColor color,
) => sdlWriteSurfacePixelFloat(
  surface,
  point.x,
  point.y,
  color.r,
  color.g,
  color.b,
  color.a,
);
