name: sdl3
description: A Dart library for accessing common SDL3 (and SDL3_image, SDL3_mixer, SDL3_net, SDL3_ttf, SDL3_gfx, SDL3_shadercross) APIs using, FFI.
version: 2.8.0
homepage: https://github.com/sansuido/sdl3
repository: https://github.com/sansuido/sdl3

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  ffi: ^2.2.0

dev_dependencies:
  change_case: ^2.2.0
  halildurmus_lints: ^2.0.0